type = "webpack"
name = "drive"
workers_dev = true
webpack_config = "webpack.config.js"
account_id  = "8c50494cddceb8025eb56e2256d00fee"
kv_namespaces = [
    { binding = "sa", id = "023bbe72e9c649188b19913078a0d768" }
]